[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Build command - fix rollup optional dependencies bug
  command = "rm -rf node_modules package-lock.json && npm cache clean --force && npm install && npm run build"

[dev]
  # Port for the framework server
  targetPort = 3000
  
  # Port for the Netlify Dev server
  port = 8888
  
  # Auto-install dependencies
  autoLaunch = false
  
  # Allow external API calls
  external = true

[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Directory for Netlify Functions
  directory = "netlify/functions"

[functions."lead-qualification"]
  timeout = 120

[functions."lead-qualification-status"]
  timeout = 30

[functions."lead-qualification-get-status"]
  timeout = 30

[functions."chatbot"]
  timeout = 30

[context.dev.environment]
  # Allow external API calls
  NETLIFY_DEV_EXTERNAL = "true"
  NETLIFY_DEV_HTTPS = "true"

# Configure secrets scanning to ignore Supabase anonymous key
# (which is designed to be public and safe for client-side use)
[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY"

# Add environment variables for all contexts
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"
