[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command
  command = "npm run build"

[dev]
  # Port for the framework server
  targetPort = 3000
  
  # Port for the Netlify Dev server
  port = 8888
  
  # Auto-install dependencies
  autoLaunch = false
  
  # Allow external API calls
  external = true

[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Directory for Netlify Functions
  directory = "netlify/functions"

[context.dev.environment]
  # Allow external API calls
  NETLIFY_DEV_EXTERNAL = "true"
  NETLIFY_DEV_HTTPS = "true"
  # Allow outbound HTTPS connections
  NODE_TLS_REJECT_UNAUTHORIZED = "0"
